package diplom.gorinych.domain.utils


const val USERS ="tb_users"
const val ID ="id"
const val NAME ="name"
const val PASSWORD ="password"
const val IS_BLOCKED ="is_blocked"
const val ROLE ="role"

const val HOUSE ="tb_house"
const val TYPE ="type"
const val MIDDLE_RANG ="middle_rang"
const val DESCRIPTION ="description"
const val IS_CONDITIONER ="is_conditioner"
const val IS_REFRIGERATOR ="is_refrigerator"
const val IS_SWIMMING_POOL ="is_swimming_pool"
const val IS_CLEANING_SERVICE ="is_cleaning_service"
const val IS_WIFI ="is_wifi"
const val IS_YOGA ="is_yoga"
const val LONGITUDE ="longitude"
const val LATITUDE ="latitude"
const val PRICE ="price"
const val COUNT_ROOMS ="count_rooms"

const val HISTORY ="tb_history"
const val ID_USER ="id_user"
const val ID_HOUSE ="id_house"
const val DATA_BEGIN ="data_begin"
const val DATA_END ="data_end"
const val RESERVATION ="reservation"
const val CONFIRM_RESERVATION ="confirm_reservation"

const val FEEDBACK ="tb_feedback"
const val CONTENT ="content"
const val RANG ="rang"
const val DATE_FEEDBACK ="DATE_FEEDBACK"

const val FORMAT_YYYY_MM_DD ="yyyy-MM-dd"
const val LOCAL_RU ="Ru"
